name: Validate standard branch name
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  branchName:
    name: Hello World Job Name
    runs-on: ubuntu-latest
    outputs:
      default: Hello World Ouput
    steps:
      - name: My package action
        id: myPackage
        uses: j1myx/githubactionbase@v1.0
        with:
          word: 'Hello World'
      - name: Get the output time
        run: echo "The time was ${{ steps.myPackage.outputs.result }}"